import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/home/Header";
import Navigation from "./components/home/Navigation";
import { LogsProvider } from "./context/LogsContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body>
        <LogsProvider>
          <div className="min-h-screen bg-neutral-950 text-white flex flex-col">
            <Header />
            <main className="flex-1 px-4 py-6 pb-24 max-w-md mx-auto w-full">
              {children}
            </main>
            <Navigation />
          </div>
        </LogsProvider>
      </body>
    </html>
  );
}
